#-----------------------------------------------------------------------------------------------------------------------
# Security settings
#-----------------------------------------------------------------------------------------------------------------------
security:
  oauth2:
    providers:
      google:
        client-secret-file: /home/np/settings/cloud.google.classmate/client_secret.txt
      facebook:
        client-secret-file: /home/np/settings/facebook.classmate/app_secret.txt
